name: Docker Image CI with Tag

on:
  push:
    tags:
      - '*'

jobs:
  push_to_registry:
    name: Push tagged docker image to dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ysde/docker-grafana-backup-tool

      - name: Extract metadata (tags, labels) for Docker (Slim version)
        id: meta_slim
        uses: docker/metadata-action@v4
        with:
          images: ysde/docker-grafana-backup-tool
          flavor: |
            latest=auto
            suffix=-slim,onlatest=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image slim version
        uses: docker/build-push-action@v4
        with:
          file: ./DockerfileSlim
          push: true
          tags: ${{ steps.meta_slim.outputs.tags }}
          labels: ${{ steps.meta_slim.outputs.labels }}
